codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%

comment:
  layout: "diff, flags"
  require_changes: true

flags:
  server:
    paths:
      - ".*\.py"
    carryforward: true
  ui-tests:
    paths:
      - ".*\.js"
    carryforward: true